#lang racket
(require "latex.rkt")

(provide (all-defined-out))

(define alpha (command 'alpha))
(define Alpha (command 'Alpha))
(define beta (command 'beta))
(define Beta (command 'Beta))
(define gamma (command 'gamma))
(define Gamma (command 'Gamma))
(define epsilon (command 'epsilon))
(define Epsilon (command 'Epsilon))
(define omega (command 'omega))
(define Omega (command 'Omega))
(define theta (command 'theta))
(define eta (command 'eta))
(define zeta (command 'zeta))
(define mu (command 'mu))
(define nu (command 'nu))
(define tau (command 'tau))
(define Tau (command 'Tau))
(define phi (command 'phi))
(define psi (command 'psi))
(define rho (command 'rho))
(define lam (command 'lambda))
(define kappa (command 'kappa))
(define chi (command 'chi))
